apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlinestore-rc
spec:
   replicas: 2
   selector: 
     app: myonlinestore
     version: 2.6.2
     
   template:
     metadata:
       labels:
          app: myonlinestore
          version: 2.6.2
          
     spec:
        containers:
        - name: myonlinestore-container   
          image: skumarjp555/javaimage1303:1
          ports:
          - containerPort: 8080